### PR TITLE
Integrating with Homepage

### PR DESCRIPTION
**Pull request by florentianayuwono**
@thngyuxuan Do you know how we can integrate this with the homepage?

### CODE REVIEW

**Comment by thngyuxuan** [comment]
for this PR, how about I take your main.dart file and integrate it with the rest of the app on my local machine. afterwards i will push on the main branch, you may then pull from main and continue adding the rest of the screens from there. because i've created a separate folder called 'screens' where it stores the other pages of the web app, so for the rest of the pages we can just add the dart files into the 'screens' folder. lmk your thoughts on this, thanks!

**Comment by thngyuxuan** [comment]
also shld we git ignore the .dart_tool/chrome-device/Default folder? seems like it's a cache folder or sth so it'll always be different for us and will keep causing merge conflicts

**Comment by florentianayuwono** [comment]
Yup, sounds great! Thank you yuxuan :D

**Comment by thngyuxuan** [comment]
orite will proceed, thanks floren!! :)

**Pull request closed without merging**
