### PR TITLE
Create Reference Page

### PR DESCRIPTION
**Pull request by florentianayuwono**

### CODE REVIEW

**Comment by thngyuxuan** [comment]
Hi Floren, I've (accidentally lol) merged your reference page to main branch, can you help me check if everything is correct? if it is you can delete your branch and this pr. thanks!!

**Comment by florentianayuwono** [comment]
Wait but I thought you cannot merge until the conflicts have been resolved? Otherwise I can just delete this PR haha.

**Comment by florentianayuwono** [comment]
Eh wait, how about the reference page Ishita has also worked on? iirc she said something about finishing her own version few days ago.

**Comment by thngyuxuan** [comment]
i did it manually hahaha. because your branch doesnt have the gitignore file yet so it'll have the merge conflicts

regarding Ishita's ref page, I've checked her branch, doesnt seem to have any recent updates

**Pull request closed without merging**
